linux-system-roles/ha_cluster

tasks/enable-repositories/CentOS.yml
tasks/enable-repositories/Fedora.yml
tasks/enable-repositories/RedHat.yml
tasks/install-and-configure-packages.yml
vars/CentOS_8.0.yml
vars/CentOS_8.1.yml
vars/CentOS_8.2.yml
vars/CentOS_8.yml
vars/RedHat_8.yml
vars/RedHat_9.yml

This pull request fixes two issues:
* In CentOS 8.3, the `HighAvailability` repository got renamed to `ha`. I updated the role to reflect that.
* Tasks for enabling repositories have been extracted to separate files. This way, tasks for new platform/version can be added in the same way as variable files.

Fix issues related to enabling repositories

---

tasks/presharedkey.yml

lookup('file') does not work with binary files and causes failures depending on the content of a preshared key file

fix reading preshared keys

---

tasks/presharedkey.yml
tests/tasks/fixture_psks.yml
vars/main.yml

OpenSSL is used in the role and automated tests to generate random
preshared keys. Previously, OpenSSL was a dependency of pcs. That is no
longer the case since pcs-0.10.8-2.
In the role, keys are no longer generated on the controller, so the role
does not install OpenSSL there. Instead, preshared keys are now
generated on target nodes and the role newly ensures OpenSSL is installed on
target nodes.
In tests, OpenSSL is needed on the controller to test cases when
preshared keys are distributed from the controller. Tests ensure OpenSSL
is installed on the controller.

do not fail if openssl is not installed

---

tasks/install-and-configure-packages.yml

Ansible 2.11 has strict checking for password_hash salt length.
If the given salt length is not equal to, or greater than, the
salt length for the hash algorithm (depending on the algorithm, the
salt length must be equal, or less than), Ansible will emit an
error like "invalid salt size".  To fix this, use the `truncate`
filter to ensure the salt length is not too long.

fix password_hash salt length

---

tests/tasks/fixture_psks.yml

in the test helper task tests/tasks/fixture_psks.yml.
This is to avoid using the non ansible-core module.

Use the openssl command-line interface instead of the openssl module

---

tasks/enable-repositories/RedHat.yml

The `rhsm_repository` module is not supported by ansible-core, so
use the subscription-manager cli instead.

replace rhsm_repository with subscription-manager cli

---

README.md
defaults/main.yml

Previously, permissions were set for 'hacluster' group. Correct name of the group is 'haclient'.

fix default pcsd permissions

---

README.md
defaults/main.yml
examples/sbd.yml
handlers/main.yml
tasks/check-and-prepare-role-variables.yml
tasks/cluster-enable-disable.yml
tasks/cluster-setup-pcs-0.10.yml
tasks/cluster-start-and-reload.yml
tasks/create-and-push-cib.yml
tasks/install-and-configure-packages.yml
tasks/main.yml
tasks/sbd.yml
templates/sbd
templates/sbd.j2
tests/tasks/cleanup_sbd.yml
tests/tasks/setup_sbd.yml
tests/tests_cib_constraints_create.yml
tests/tests_sbd_all_options.yml
tests/tests_sbd_check_devices_count.yml
tests/tests_sbd_defaults.yml
tests/tests_sbd_defaults_disabled.yml
vars/main.yml

As discussed in #29 I started implementing my workarounds in order to support SBD.
This is **not** considered as *ready to merge*, yet. I was able to use this code in order to configure SBD on a 2-node cluster using the following code:
```yaml
- name: linux-system-roles.ha_cluster
ha_cluster_cluster_name: "{{ cluster_name }}"
ha_cluster_hacluster_password: "{{ cluster_password }}"
ha_cluster_resource_primitives:
- id: fence-sbd
agent: 'stonith:fence_sbd'
instance_attrs:
- attrs:
- name: devices
value: /dev/sdb
ha_cluster_resource_groups: "{{ cluster_groups }}"
ha_cluster_sbd_enable: true
ha_cluster_sbd_devices:
- /dev/sdb
ha_cluster_sbd_startmode: "clean"
```
Currently, there are still two TODOs:

add SBD support

---

tasks/install-and-configure-packages.yml

To make sure the string is strictly truncated at the given length, add leeway=0.
It looks `truncate` does not always truncate the string depending upon the length of the given string. In this example, when the length is 20, the entire string is kept without the 4th argument.
Sample test:
```
---
- name: set parameters for test
hosts: localhost
gather_facts: false
vars:
str_len_20: "01234567890123456789"
str_len_22: "0123456789012345678901"
tasks:
- debug:
msg: "str_len_20 truncate(16, True, '') {{ str_len_20|truncate(16, True, '') }}"
- debug:
msg: "str_len_20 truncate(16, True, '', 0) {{ str_len_20|truncate(16, True, '', 0) }}"
- debug:
msg: "str_len_22 truncate(16, True, '') {{ str_len_22|truncate(16, True, '') }}"
- debug:
msg: "str_len_22 truncate(16, True, '', 0) {{ …
```

additional fix for password_hash salt length

---

CHANGELOG.md

[1.7.4] - 2022-07-19
- none
- readme: describe limitations of udp transports (#56)
- make all tests work with gather_facts: false (#52)
Ensure tests work when using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml (#53)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#54)

Version 1.7.4 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

[1.7.5] - 2022-09-19
- none
- only install and setup fence-virt on x86_64 hosts (#64)
fence-virt is not available for any architecture other than x86_64
- replace yes, no, default with true, false, d
Use `true`, `false`, and `d` instead of `yes`, `no`, and `default`
- readme: update SBD example (#61)

Version 1.7.5 - CHANGELOG.md [citest skip]

---

tests/tasks/fixture_psks.yml
tests/tests_cluster_basic_custom_pcsd_tls.yml
tests/tests_cluster_basic_existing_psks.yml
tests/tests_cluster_basic_new_psks.yml

The tests were writing generated secrets to the directory tests/tmp
which is shared by all tests when running tests in parallel.
Instead, create a real temporary directory for these secrets for the
tests that use generated secrets.

use a real temporary directory for test secrets

---

README.md
defaults/main.yml
meta/collection-requirements.yml
tasks/firewall.yml
tasks/main.yml
tasks/selinux.yml
tests/tasks/check_firewall_selinux.yml
tests/tests_cib_constraints_create.yml
tests/tests_cib_properties_empty.yml
tests/tests_cib_properties_one_set.yml
tests/tests_cib_resources_create.yml
tests/tests_cluster_advanced_knet_full.yml
tests/tests_cluster_advanced_knet_implicit.yml
tests/tests_cluster_advanced_udp_full.yml
tests/tests_cluster_basic.yml
tests/tests_cluster_basic_custom_fence_agents.yml
tests/tests_cluster_basic_custom_packages.yml
tests/tests_cluster_basic_custom_pcsd_tls.yml
tests/tests_cluster_basic_disabled.yml
tests/tests_cluster_basic_existing_psks.yml
tests/tests_cluster_basic_new_psks.yml
tests/tests_cluster_destroy.yml
tests/tests_sbd_all_options.yml
tests/tests_sbd_defaults.yml
tests/tests_sbd_defaults_disabled.yml
tests/tests_sbd_needs_atb_while_atb_enabled.yml

- Introduce ha_cluster_manage_firewall to use the firewall role to manage the high-availability service and the fence-virt port. ha_cluster_manage_firewall is set to true, by default.
- Introduce ha_cluster_manage_selinux to use the selinux role to manage the ports in the high-availability service. ha_cluster_manage_selinux is set to true, by default.
- Add the test check task tasks/check_firewall_selinux.yml for verify the ports status.
- Add meta/collection-requirements.yml.

Use the firewall role and the selinux role from the ha_cluster role

---

README.md
defaults/main.yml
examples/create-pcsd-cert.yml
tasks/check-and-prepare-role-variables.yml
tasks/pcs-configure-pcs-pcsd.yml
tests/tests_cluster_basic_custom_pcsd_tls_cert_role.yml

- Introduce a variable ha_cluster_pcsd_certificates to set the certificate_requests.
- Add a test test script tests/tests_cluster_basic_custom_pcsd_tls_cert_role.yml
I borrowed the mssql README in https://github.com/linux-system-roles/mssql/pull/125 written by @spetrosi. Thanks, Sergei!
@spetrosi, @tomjelinek, this is another piece of the effort to use other roles in the ha_cluster role. If you could review it, I'd greatly appreciate it.

Use the certificate role to create the cert and the key

---

README.md

I'd like to add this note by @richm to all the system roles using the certificate role.
https://github.com/linux-system-roles/logging/pull/295#discussion_r1003844984
Thanks!

Add a note on the certificate role usage to README.

---

CHANGELOG.md

[1.8.0] - 2022-11-01
- Use the firewall role and the selinux role from the ha_cluster role
- Introduce ha_cluster_manage_firewall to use the firewall role to
manage the high-availability service and the fence-virt port.
Default to false - means the firewall role is not used.
- Introduce ha_cluster_manage_selinux to use the selinux role to
manage the ports in the high-availability service.
Assign cluster_port_t to the high-availability service ports.
Default to false - means the selinux role is not used.
- Add the test check task tasks/check_firewall_selinux.yml for
verify the ports status.
Note: This pr changes the ha_cluster role's behavior slightly.
It used to configure firewall without any settings if the firewall
service is enabled. With this change made by this …

Version 1.8.0 - CHANGELOG.md [citest skip]

---

README.md

The long heading causes problems with md to adoc conversion.  Shorten
the length by using abbreviations.

long heading causes problems with md to adoc conversion

---

CHANGELOG.md

[1.8.1] - 2022-11-14
- none
- none
- long heading causes problems with md to adoc conversion
The long heading causes problems with md to adoc conversion.  Shorten
the length by using abbreviations.

Version 1.8.1 - CHANGELOG.md [citest skip]

---

tasks/enable-repositories/CentOS.yml
tasks/enable-repositories/RedHat.yml

If users want to suppress the warning, users will need to configure ansible.cfg.

command warn is not supported in ansible-core 2.14

---

tasks/test_cleanup_qnetd.yml
tests/tests_qdevice_minimal.yml
tests/tests_qnetd.yml
tests/tests_qnetd_disabled.yml

Ensure that qnetd package is not installed and there are no qnetd config files present to verify that the role really installs and creates those. This also sets test environment to a clearly defined and correct state, which is needed in case tests are not isolated.

tests: add qnetd cleanup

---

CHANGELOG.md

[1.8.3] - 2022-12-12
- none
- command warn is not supported in ansible-core 2.14
If users want to suppress the warning, users will need to configure
ansible.cfg.
- fix ownership of cib.xml
- update for upcoming pcs release
The upcoming pcs brings stricter validation for resource
configuration to prevent certain types of misconfiguration.
- tests: add qnetd cleanup
- none

Version 1.8.3 - CHANGELOG.md [citest skip]

---

tasks/cluster-enable-disable.yml
tests/tests_sbd_defaults_disabled.yml

follow up PR from #78 with no `/` in branch name.
Currently the `sbd.service`will not be enabled if the cluster autostart is disabled. This is not intended behavior as is will effectively break the feature.
We can simply remove the condition to depend on `ha_cluster_start_on_boot` as on a RHEL8 system the `sbd.service` has a dependencies (`Before/After/PartOf/RequiredBy`) to cluster related services which make sure it is only ever started by the cluster (a manual start is not possible).
```
[Unit]
[...]
Before=pacemaker.service
Before=dlm.service
After=systemd-modules-load.service iscsi.service
PartOf=corosync.service
[...]
[Install]
RequiredBy=corosync.service
RequiredBy=pacemaker.service
RequiredBy=dlm.service
```

Allow enabled SBD on disabled cluster

---

CHANGELOG.md

[1.8.4] - 2022-12-13
- none
- Allow enabled SBD on disabled cluster (#81)
Currently the sbd.service will not be enabled if the cluster autostart
is disabled. This is not intended behavior as is will effectively break
the feature. We can simply remove the condition to depend on
ha_cluster_start_on_boot as on a RHEL8 system the sbd.service has a
dependencies (Before/After/PartOf/RequiredBy) to cluster related
services which make sure it is only ever started by the cluster (a
manual start is not possible).
- none

Version 1.8.4 - CHANGELOG.md [citest skip]

---

tasks/check-and-prepare-role-variables.yml
tasks/main.yml

When running the role with ha_cluster_cluster_present: false to purge cluster passwords are not required

Not request password to be specified when purging cluster

---

CHANGELOG.md

[1.8.5] - 2023-01-13
- none
- Not request password to be specified when purging cluster (#92)
When running the role with ha_cluster_cluster_present: false to purge
cluster passwords are not required
Add a missing bool mapping
do not set hacluster password when it is empty
- ansible-lint 6.x fixes (#94)
- Add check for non-inclusive language (#97)

Version 1.8.5 - CHANGELOG.md [citest skip]

---

tasks/selinux.yml
tests/tasks/check_firewall_selinux.yml

Add the condition to tests/tasks/check_firewall_selinux.yml and tasks/selinux.yml.

Fence agent firewall port is restricted to x86_64 architecture.

---

CHANGELOG.md

[1.8.6] - 2023-02-02
- none
- Fence agent firewall port is restricted to x86_64 architecture. (#106)
- none

Version 1.8.6 - CHANGELOG.md [citest skip]

---

tasks/cluster-start-and-reload.yml
tasks/sbd.yml

Fix a corner case bug occuring with pcs 0.10.15 and newer and pcs 0.11.4 and newer:
When setting `stonith-watchdog-timeout` in a stopped cluster, `cib.xml.sig` is not modified by pcs. This leads to pacemaker ignoring new `cib.xml` content and read configuration from a previous version of cib, effectively reverting `stonith-watchdog-timeout` update done by the role. Pacemaker then exits with an error and the role fails, unable to proceed and configure the cluster.
With old pcs versions, removing `cib.xml.sig` has no adverse effects. There is no need to check for pcs version when removing the file.

Fix stonith watchdog timeout

---

templates/sbd

Add role name to the generated config files. 
```
```
Note: This info is introduced to help customers to identify that it was generated by System Roles. Also, it could be used in future analysis.

Fingerprint RHEL System Role managed config files

---

README.md
examples/sbd.yml
meta/collection-requirements.yml
tasks/sbd.yml
tasks/test_setup_sbd.yml
tests/tests_sbd_all_options.yml

follow up PR from #79 with no `/` in branch name.
SBD needs a watchdog device to work. The watchdog device is created by loading one or more watchdog kernel modules. The modules can be configured on a per node basis. Blocking certain modules from being loaded is also often a use case (e.g due to hardware specifics).

Add possibility to load SBD watchdog kernel modules

---

tasks/cluster-setup-keys.yml
tasks/cluster-start-and-reload.yml
tasks/create-and-push-cib.yml
tasks/enable-repositories/CentOS.yml
tasks/enable-repositories/RedHat.yml
tasks/pcs-qnetd.yml
tasks/test_setup_sbd.yml

Ansible lint now requires the use of `changed_when:` with commands
even in some cases where the command has a `when` condition.

fix ansible-lint issues with changed_when, others

---

tests/tasks/check_header.yml
tests/templates/get_ansible_managed.j2
tests/tests_sbd_all_options.yml

Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes these parameters.  `fingerprint` is required,
and one of `__file` or `__file_content`:
* `__file` - the full path of the file to check e.g. `/etc/realmd.conf`
* `__file_content` - the output of `slurp` of the file
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#adding-comments-to-fi …

test: check generated files for ansible_managed, fingerprint

---

README.md

For roles that use other system roles, they have a
`meta/collection-requirements.yml` file, and the README lists
these requirements and instructions.  However, these are only
required for github and Galaxy users, and not for users who
use the packaged roles, where it is confusing to see instructions
about installing requirements when none are needed.  We need to
make it easier to remove these sections when packaging.
Fix some ansible-lint and markdownlint issues.

docs: fix collection requirements section

---

README.md
tasks/shell_pcs/pcs-auth-pcs-0.10.yml

Enhancement: cluster and quorum can have distinct passwords
Reason: The same quorum hosts can be joined to multiple, separate clusters. Since the passwords of the "hacluster" user on these clusters might be different, it makes sense to configure them separately.
Result: I separated `pcs auth` for the cluster and qdevice. I also introduced an new var `ha_cluster_hacluster_qdevice_password`, which is used for qdevice auth. If the new var is not set, qdevice auth will fall back to use `ha_cluster_hacluster_password` like rest of the cluster. This should make the change fully backwards compatible. 
Issue Tracker Tickets (Jira or BZ if any): none

feat: cluster and quorum can have distinct passwords

---

.gitlab-ci.yml
README.md
defaults/main.yml
examples/stonith-levels.yml
tasks/shell_pcs/check-and-prepare-role-variables.yml
tasks/shell_pcs/create-and-push-cib.yml
tasks/shell_pcs/pcs-cib-stonith-level.yml
tests/tests_cib_stonith_levels.yml
tests/tests_cib_stonith_levels_validation.yml

Enhancement:
Add support for configuring stonith levels, also known as fencing topology
Reason:
This is required so users can configure multi-level fencing or fencing of machines with redundant power sources
Result:
The role is capable of configuring stonith levels, also known as fencing topology
[RHEL-4624](https://issues.redhat.com/browse/RHEL-4624)

feat: Add support for configuring stonith levels

---

README.md
defaults/main.yml
tasks/enable-repositories/CentOS.yml
tasks/enable-repositories/RedHat.yml
vars/CentOS_9.yml
vars/RedHat_8.yml
vars/RedHat_9.yml

Enhancement:
add an option to enable Resilient Storage rpm repo
Reason:
to be able to install dlm and gfs2 packages
Result:
there's a new variable in the role which enables Resilient Storage rpm repo so that dlm and gfs2 packages can be installed
https://issues.redhat.com/browse/RHEL-14090

feat: add an option to enable Resilient Storage rpm repository

---

templates/sbd

Cause: Some versions of Ansible/Jinja have a problem with evaluating
a non-string value as a string inside of a macro.
Consequence: Ansible will give an error that a templated value
is not a string.
Fix: Cast the value to a string.
Result: Ansible correctly templates the variable with no errors.

fix: cast sbd option value to string

---

tasks/shell_pcs/check-and-prepare-role-variables.yml

Do not use `select("true")`.  This causes an error with Ansible 2.9
with Jinja 2.7 because there is no `true` test.  Instead, just rely
on the default behavior of `select` to evaluate the argument in a
boolean context.
https://jinja.palletsprojects.com/en/2.9.x/templates/#select
`If no test is specified, each object will be evaluated as a boolean.`

test: do not use true test with select

---

.ansible-lint
.ostree/get_ostree_data.sh
README.md
meta/collection-requirements.yml
tasks/enable-package-repositories.yml
tasks/main.yml
tasks/set_vars.yml
tasks/test_cleanup_qnetd.yml
tasks/test_setup.yml
tasks/test_setup_qnetd.yml
tests/tasks/fixture_psks.yml
tests/tests_cluster_basic_custom_fence_agents.yml
tests/tests_cluster_basic_custom_packages.yml
tests/tests_qdevice_tls_kaptb_options.yml

The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …

refactor: improve support for ostree systems

---

.gitlab-ci.yml
README.md
tasks/shell_pcs/sbd.yml
templates/override-timeout.conf
tests/tests_sbd_all_options.yml
tests/tests_sbd_delay_start.yml

Enhancement:
Add capability to override a timeout of sbd.service
Reason:
Timeout for starting the sbd.service needs to be longer than SBD_START_DELAY, otherwise the start of the sbd.service times out and prevents a cluster from starting
Result:
Cluster starts even when high value of SBD_START_DELAY is set
https://issues.redhat.com/browse/RHEL-4684

fix: set sbd.service timeout based on SBD_START_DELAY

---

.ostree/get_ostree_data.sh
.sanity-ansible-ignore-2.13.txt
.sanity-ansible-ignore-2.14.txt
.sanity-ansible-ignore-2.15.txt
.sanity-ansible-ignore-2.16.txt

Use the `#!/usr/bin/env bash` shebang which is ansible-test friendly.
This means we can remove get_ostree_data.sh from the .sanity* files.
This also means we can remove the .sanity* files if we do not need
them otherwise.
Rename `pth` to `path` in honor of nscott

refactor: get_ostree_data.sh use env shebang - remove from .sanity*

---

tests/tests_sbd_all_options.yml

Fix the error reported by recent Ansible versions: Conditional statements should not include jinja2 templating delimiters. Conditional is marked as unsafe, and cannot be evaluated.

test: fix jinja templates in conditionals

---

.ansible-lint
.gitlab-ci.yml
library/pcs_api_v2.py
library/pcs_qdevice_certs.py
module_utils/ha_cluster_lsr/pcs_api_v2_utils.py

This branch updates downstream GitLab CI configuration to match changes done to upstream CI to support recent ansible-lint. It also fixes issues reported by woke, isort, pylint and mypy linters.

style: followup for recent ansible-lint related changes

---

README.md

docs: change Supported to Compatible

---

README.md
tasks/enable-repositories/Suse.yml
tasks/main.yml
tasks/shell_crmsh/check-and-prepare-role-variables.yml
tasks/shell_crmsh/cluster-destroy-crm.yml
tasks/shell_crmsh/cluster-setup-corosync.yml
vars/Suse.yml

Enhancement: Adds additional steps for SLES15 enablement:
- High Availability Extension detection
- Package list updated to remove SLES4SAP specific package
- Cluster destroy adjusted to avoid failure when corosync-qdevice was not present
- Removed logd check, because it is part of cluster packages and it should not be checked before packages are installed on SLES15
- Added gather facts for NIC for corosync template.
Additionally main.yml was reordered to allow variable checks before package installation.
Readme was updated to note higher Service Pack requirement for both SLES and SLES4SAP, because of detected dependency on pattern patterns-ha-ha_sles, which failed to install using package module because of samba client version mismatch.
Reason: Adding coverage for SLES15 after cluster …

feat: SLES15 enablement, HAE detection

---

.gitlab-ci.yml
README.md
defaults/main.yml
examples/acls.yml
tasks/shell_pcs/create-and-push-cib.yml
tasks/shell_pcs/pcs-cib-acls.yml
tests/tests_cib_acls.yml

Enhancement:
Add support for configuring  ACL
Reason:
This is necessary so that users can control access to different parts of the CIB
Result:
It is now possible to configure ACL using the role
https://issues.redhat.com/browse/RHEL-17271

feat: Add support for ACL

---

.gitlab-ci.yml
README.md
defaults/main.yml
tasks/main.yml
tests/tests_cluster_basic_cloud_packages.yml
vars/CentOS_8.yml
vars/CentOS_9.yml
vars/Fedora.yml
vars/RedHat.yml
vars/RedHat_8.yml
vars/RedHat_9.yml
vars/Suse.yml

Enhancement:
Make it easier to install agents for cloud environments.
Reason:
The agents are not installed by default. Even though users can install them by other means, we want to provide a variable to install them easily.
Result:
Setting `ha_cluster_install_cloud_agents` variable to `true` installs cloud agents.
[RHEL-27186](https://issues.redhat.com/browse/RHEL-27186)
#185

feat: easily install cloud agents

---

.gitlab-ci-tier1.yml.j2
.gitlab-ci.yml

Enhancement:
* use child pipelines to overcome jobs per pipeline limits
* make collecting logs actually work
* get list of tier1 tests automatically
Reason:
get the CI working after recent gitlab changes
Result:
CI is working
None

ci: fix internal gitlab CI

---

README.md
tasks/shell_pcs/pcs-node-attributes.yml
tests/tests_cib_node_attributes.yml

Enhancement:
Handle node attributes with multiple attributes sets consistently with rest of the role.
Reason:
Node attributes multiple sets was handled in a manner inconsistent with the rest of the role. Instead of using only the first set and ignoring the rest, multiple sets was merged into one single set. Such inconsistency can confuse a user and may complicate the possible future addition of support for multiple sets.
Result:
Node attributes multiple set are handled consistently with the rest of the role. This behavior is also described more explicitly in README.md.
https://issues.redhat.com/browse/RHEL-33076

fix: make consistent approach for multiple node attributes sets

---

README.md
examples/utilization.yml
tasks/shell_pcs/create-and-push-cib.yml
tasks/shell_pcs/pcs-cib-resource-primitive.yml
tasks/shell_pcs/pcs-node-utilization.yml
tests/tests_cib_utilization.yml

Enhancement:
Add support for configuring utilization attributes.
Reason:
This is necessary so that user can configure utilization attributes for node and primitive resource..
Result:
It is now possible to configure utilization attributes  using the role.
https://issues.redhat.com/browse/RHEL-33532

feat: Add support for utilization

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-plugin-scan.yml
.github/workflows/ansible-test.yml
.github/workflows/python-unit-test.yml
.yamllint.yml
tasks/shell_pcs/cluster-setup-corosync.yml
tasks/shell_pcs/cluster-setup-keys.yml
tasks/shell_pcs/configure-shell.yml
tasks/shell_pcs/create-and-push-cib.yml
tasks/shell_pcs/sbd.yml
tests/tasks/fixture_psks.yml
tests/tasks/qnetd_backup_restore.yml
tests/tests_cluster_basic_existing_psks.yml
tests/tests_cluster_basic_new_psks.yml
tox.ini

The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …

ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

---

.gitlab-ci-tier1.yml.j2

Fix Python discovery with Ansible 2.17+ in gitlab CI. Also, make the gitlab CI script more verbose and replace if-then-else with && or ||.

ci: fix Python discovery with Ansible 2.17+

---

templates/crmsh_corosync.j2

Enhancement:
- Remove predefined parameters from corosync j2 template for crmsh that were assigning default value
- Reuse existing corosync variables similar to pcs task
Reason:
- Remove dependency on SAP and provide cleaner and lightweight corosync.conf
Result:
- Successfully tested on SLES15 SP5 for SAP HANA and SAP ASCS clusters.

feat: crmsh corosync jinja2 template rework

---

tasks/shell_crmsh/sbd.yml

Enhancement:
- Remove obsolete assert for softdog, which was not working
- Add default `softdog`, to avoid issue when /dev/watchdog is not present causing SBD service to fail.
Reason:
- Assert code was causing inherent dependency on `sbd_watchdog_modules`, which should be optional, but it would not work without softdog present.
- Correction after implementing SBD support in https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_ha_pacemaker_cluster
Result:
- Tested and verified on SLES4SAP 15.

feat: crmsh watchdog correction, remove obsolete assert for softdog

---

README.md
defaults/main.yml
examples/alerts.yml
tasks/shell_pcs/create-and-push-cib.yml
tasks/shell_pcs/pcs-cib-alerts.yml
tests/tests_cib_alerts.yml

Enhancement:
Add support for configuring Pacemaker Alerts
Reason:
This is necessary so that users can configure alerts to take some external action when a cluster event occurs (node failure, resource starting or stopping, etc.)
Result:
It is now possible to configure Pacemaker Alerts using the role
https://issues.redhat.com/browse/RHEL-45285

feat: Add alerts support

---

README.md
examples/sbd.yml

Enhancement:
Fix documentation and examples regarding configuring SBD devices in fence_sbd agent.
Reason:
`ha_cluster.sbd_devices` variable is used in examples even though it isn't defined. In other example the variable is defined, but its content depends on the node the task is executed on, which is bad practice for configuring sbd.
Result:
Examples and documentation are updated to show a recommended way of configuring SBD devices.
https://issues.redhat.com/browse/RHELDOCS-18172

docs: fix sbd_devices documentation and examples

---

.gitlab-ci.yml
tasks/main.yml
tasks/shell_pcs/pcs-cib-resource-primitive.yml
tests/tasks/assert_cluster_running.yml
tests/tests_cib_constraints_create.yml

This makes the role work with the upcoming version of pcs and cluster stack in general.
It also addresses the removal of password_hash filter due to removal of passlib.

fix: Fixes for new pcs and ansible

---

vars/RedHat.yml
vars/Suse.yml

openssl is now used to generate passwords, so make it
a required basic package.

fix: openssl is now required for password

---

README.md
defaults/main.yml
tasks/main.yml
tasks/shell_crmsh/create-and-push-cib.yml
tasks/shell_crmsh/crm-cluster-properties.yml

- package installation changed from `present` to `latest` to accommodate for installation of package updates.
- Images do not come with latest maintenance patches so it is better to update to latest before building cluster.
- @richm @tomjelinek yum should support state `latest` from what I checked.
- New variable added to allow updating of packages `ha_cluster_use_latest_packages`, as discussed below. 
- Changed maintenance tasks to force mode (expect modules were commented out)
- Add task to disable `stonith-enabled` property before proceeding with other `crm configure` steps
- Move cluster property task to end of CIB build so stonith can be enabled at end
- Enhance cluster property task to
- Append `stonith-enabled=true` if it is missing.
- Show warning if it was purposefully executed …

feat: crmsh 4.6.0 support and stonith-enabled workflow update

---

tests/vars/rh_distros_vars.yml
vars/AlmaLinux_10.yml
vars/AlmaLinux_8.yml
vars/AlmaLinux_9.yml
vars/Rocky_10.yml
vars/Rocky_8.yml
vars/Rocky_9.yml
vars/main.yml

We have a lot of requests to support Rocky and Alma in various system roles. The
first part of adding support is adding `vars/` files for these platforms. In
almost every case, for a given major version N, the vars file RedHat_N.yml can
be used for CentOS, Rocky, and Alma.  Rather than making a copy of the
RedHat_N.yml file, just use a symlink to reduce size and maintenance burden, and
standardize this across all system roles for consistency.
NOTE: There is no Alma or Rocky version 7 or less.
NOTE: OracleLinux is not a strict clone, so we are not going to do this for
OracleLinux at this time.  Support for OracleLinux will need to be done in
separate PRs. For more information, see
https://github.com/linux-system-roles/cockpit/issues/130
**Question**: Why not just use …

refactor: Use vars/RedHat_N.yml symlink for CentOS, Rocky, Alma wherever possible

---

.github/config/ubuntu-requirements.txt
.github/workflows/python-unit-test.yml
.gitlab-ci.yml
.sanity-ansible-ignore-2.18.txt
tests/tasks/fetch_versions.yml
tests/tests_cib_constraints_create.yml
tests/tests_cib_rsc_op_defaults.yml
tests/tests_cib_stonith_levels.yml

Enhancement:
Update test scripts to work with the latest pcs and pacemaker versions
Reason:
Result:

ci: tests update for pcs-0.12 and pacemaker-3

---

tasks/main.yml
tests/tests_cluster_basic_cloud_packages.yml
vars/CentOS_10.yml
vars/CentOS_8.yml
vars/CentOS_9.yml
vars/Fedora.yml
vars/RedHat.yml
vars/RedHat_10.yml
vars/RedHat_8.yml
vars/RedHat_9.yml
vars/Suse.yml

Enhancement:
list cloud agent packages per architecture
Reason:
not all cloud agents are available for all architectures
Result:
role doesn't fail anymore due to it trying to install packages not available for a given architecture
https://issues.redhat.com/browse/RHEL-55538

fix: list cloud agent packages by architecture

---

tasks/shell_pcs/pcs-cib-constraint-colocation.yml
tasks/shell_pcs/pcs-cib-constraint-location.yml

Enhancement:
Update the role to pcs-0.12 command syntax
Reason:
New version of pcs brings updated syntax of some commands. Previous syntax is deprecated but it still works. It will be dropped eventually, though, and the role should be ready for that.
Result:
Role uses new pcs syntax if new enough pcs is available.
https://issues.redhat.com/browse/RHEL-45303

fix: update constraints commands syntax for pcs-0.12

---

tasks/enable-repositories/Suse.yml
tasks/set_vars.yml
tasks/shell_crmsh/create-and-push-cib.yml
tasks/shell_crmsh/crm-cib-constraint-colocation.yml
tasks/shell_crmsh/crm-cib-constraint-location.yml
tasks/shell_crmsh/crm-cib-constraint-order.yml
tasks/shell_crmsh/crm-cib-constraint-set.yml
tasks/shell_crmsh/crm-cib-constraint-ticket.yml
tasks/shell_crmsh/crm-cib-resource-clone.yml
tasks/shell_crmsh/crm-cib-resource-group.yml
tasks/shell_crmsh/crm-cib-resource-primitive.yml
tasks/shell_crmsh/crm-cib-stonith-level.yml
tasks/shell_crmsh/crm-rsc-op-defaults.yml
vars/SLES_15.yml
vars/Suse.yml

1. Remove all use of `expect` module which required Python `pexpect` module to be installed
2. Replace `expect` by using `--force` and `yes n` to skip all prompts and fail if user input is invalid or in conflict.
3. Enhance `resource_sets` handling.
- Extra python dependency was causing unnecessary dependencies
- Tested on `SLES for SAP Applications 15 SP6` in AWS for SAP HANA, SAP ASCS/ERS and dummy clusters.

feat: Remove python expect dependency in crmsh

---

module_utils/ha_cluster_lsr/info/exporter.py
tox.ini

refactor: fix python black formatting

---

tasks/shell_pcs/cluster-setup-keys.yml
tasks/shell_pcs/cluster-start-and-reload.yml
tests/tasks/assert_qdevice_in_cluster.yml
tests/tests_cluster_basic_custom_packages.yml

Enhancement:
Always restart qdevice daemon on cluster nodes when certificates for qdevice - qnetd communication have changed.
Reason:
With the restart missing, qdevice and qnetd were not able to communicate in certain scenarios. This basically rendered qdevice not working until the cluster is restarted. 
Result:
Communication between qdevice (cluster nodes) and qnetd (quorum device) works.
none

fix: restart qdevice when its certificates have been regenerated

---

README.md
library/ha_cluster_info.py
module_utils/ha_cluster_lsr/info/exporter.py
module_utils/ha_cluster_lsr/info/loader.py
tests/tests_cluster_advanced_knet_full.yml
tests/tests_cluster_advanced_knet_implicit.yml
tests/tests_cluster_advanced_udp_full.yml
tests/tests_cluster_basic.yml
tests/tests_cluster_basic_cloud_packages.yml
tests/tests_cluster_basic_disabled.yml
tests/tests_export_doesnt_destroy_cluster.yml
tests/tests_export_firewall_selinux.yml
tests/tests_pcs_permissions.yml
tests/unit/firewall_mock.py
tests/unit/test_ha_cluster_info.py
tests/unit/test_info_exporter.py
tests/unit/test_info_loader.py
vars/CentOS_10.yml
vars/CentOS_8.yml
vars/CentOS_9.yml
vars/RedHat_10.yml
vars/RedHat_8.yml
vars/RedHat_9.yml

Enhancement:
Add pcsd related and OS related variables to `ha_cluster_info` module exporting current cluster configuration.
Reason:
This is the next step in implementing an info module which exports cluster configuration in a variables structure in the same format as ha_cluster role accepts.
Result:
variables have been added to the export:
* `ha_cluster_enable_repos`
* `ha_cluster_enable_repos_resilient_storage`
* `ha_cluster_manage_firewall`
* `ha_cluster_manage_selinux`
* `ha_cluster_install_cloud_agents`
* `ha_cluster_pcs_permission_list`
https://issues.redhat.com/browse/RHEL-46224

feat: export pcsd and OS configuration

---

module_utils/ha_cluster_lsr/pcs_api_v2_utils.py

Enhancement:
Do not use proxy when connecting to local pcsd via unix socket on managed nodes.
Reason:
When a proxy is defined, it disrupts communication towards the local pcsd unix socket. This makes the role fail.
Result:
Role works even if a proxy is defined.
https://issues.redhat.com/browse/RHEL-81918

fix: disable proxy when connecting to pcsd local socket

---

tests/tests_cib_alerts.yml

Enhancement:
Update alerts test so that tehy are able to process new output format of alerts configuration in pcs
Reason:
Tests are failing with new pcs even if the role works correctly
Result:
Tests work correctly with new pcs
https://issues.redhat.com/browse/RHEL-86465

test: update alerts test for new pcs

---

tasks/enable-repositories/Suse.yml

Enhancement:
- Removes `python3-rpm` dependency caused by `ansible.builtin.package_facts`
- Improved conditional for `/etc/products.d/sle-ha.prod` file validation to not execute if package is present.
Reason:
- Removal of unnecessary dependencies as started in https://github.com/linux-system-roles/ha_cluster/pull/249
Result:
- Tested on SLES 15 SP6 on AWS with latest `crmsh` package.

feat: crmsh remove python3-rpm dependency
