tasks/test_setup.yml, tests/tests_include_vars_from_parent.yml
Ensure tests work when using ANSIBLE_GATHERING=explicit
=> make all tests work with gather_facts: false

defaults/main.yml, tasks/firewall.yml, tasks/main.yml, tests/tests_cib_resources_create.yml, tests/tests_cluster_basic.yml, tests/tests_cluster_basic_existing_psks.yml, tests/tests_cluster_basic_new_psks.yml, tests/vars/main.yml
fence-virt is not available for any architecture other than x86_64
=> only install and setup fence-virt on x86_64 hosts

README.md
- Add requirements
- Add an example
=> Update README for "use other roles from ha_cluster role".

README.md, examples/advanced-corosync.yml, examples/cluster-properties.yml, examples/constraints.yml, examples/resources.yml, examples/sbd.yml, examples/simple.yml
Recommend to set ha_cluster_manage_firewall and ha_cluster_manage_selinux to true in the examples in README.md.
Add ha_cluster_manage_firewall and ha_cluster_manage_selinux to the example playbooks.
=> Recommend to set ha_cluster_manage_firewall and ha_cluster_manage_selinux

tasks/pcs-qnetd.yml
=> fix qnetd check mode

CHANGELOG.md
[1.8.2] - 2022-11-30
- none
- fix qnetd check mode
- none
=> Version 1.8.2 - CHANGELOG.md [citest skip]

.github/workflows/woke.yml, CHANGELOG.md, README.md, examples/constraints.yml, examples/resources.yml, tasks/create-and-push-cib.yml, tests/tests_cib_constraints_create.yml, tests/tests_cib_resources_create.yml
Add check for non-inclusive language
Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Clean up / Workaround non-inclusive words
- CHANGELOG.md
- README.md
- examples/constraints.yml
- examples/resources.yml
- tasks/create-and-push-cib.yml
- tests/tests_cib_constraints_create.yml
- tests/tests_cib_resources_create.yml
=> Add check for non-inclusive language

CHANGELOG.md
[1.8.7] - 2023-02-08
- none
- Fix stonith watchdog timeout; fix purging nodes from pacemaker (#105)
- none
=> Version 1.8.7 - CHANGELOG.md [citest skip]

CHANGELOG.md
[1.9.0] - 2023-04-06
- add support for resource and operation defaults
- Add possibility to load SBD watchdog kernel modules (#82)
- use pcs to setup qdevice certificates if available
- Add README-ansible.md to refer Ansible intro page on linux-system-roles.github.io (#115)
- Fingerprint RHEL System Role managed config files (#116)
=> Version 1.9.0 - CHANGELOG.md [citest skip]

CHANGELOG.md
Create changelog update and release for version 1.9.1
=> docs(changelog): version 1.9.1 [citest skip]

CHANGELOG.md
Create changelog update and release for version 1.9.2
=> docs(changelog): version 1.9.2 [citest skip]

.github/workflows/codeql.yml, .github/workflows/python-unit-test.yml, contributing.md
ha_cluster - add to python_roles
metrics - fix ansible-lint
=> ci: update metrics ansible-lint; add ha_cluster to python_roles

CHANGELOG.md
Create changelog update and release for version 1.9.3
=> docs(changelog): version 1.9.3 [citest skip]

.github/workflows/python-unit-test.yml
=> ci: test with pcs v0.11.6

.gitlab-ci.yml, module_utils/ha_cluster_lsr/pcs_api_v2_utils.py, tasks/firewall.yml, tests/tests_cib_properties_one_set.yml, tests/tests_include_vars_from_parent.yml, tests/tests_sbd_all_options.yml
* fix: catch connection errors when calling pcsd API
* test: fix properties test for RHEL8
* style: address ansible-lint 6.17 issues
* ci: enable additional internal CI in gitlab
=> fix: various minor fixes

CHANGELOG.md
Create changelog update and release for version 1.10.0
=> docs(changelog): version 1.10.0 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.10.1
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
=> docs(changelog): version 1.10.1 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.11.0
=> docs(changelog): version 1.11.0 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.12.0
=> docs(changelog): version 1.12.0 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.13.0
=> docs(changelog): version 1.13.0 [citest skip]

tasks/main.yml, tests/tests_qnetd.yml
=> fix: manage firewall on qnetd hosts

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.13.2
=> docs(changelog): version 1.13.2 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.13.4
=> docs(changelog): version 1.13.4 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.13.5
=> docs(changelog): version 1.13.5 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.16.0
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
=> docs(changelog): version 1.16.0 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.18.0
=> docs(changelog): version 1.18.0 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.19.0
=> docs(changelog): version 1.19.0 [citest skip]

tests/tests_cib_resources_create.yml, tests/tests_cluster_basic_cloud_packages.yml
=> test: add gather_facts true for tests that need facts

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.19.1
=> docs(changelog): version 1.19.1 [citest skip]

README.md, examples/sbd.yml
Fix a typo and make the comment more clear.
=> docs: improve comments in SBD examples

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.20.0
=> docs(changelog): version 1.20.0 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.21.0
=> docs(changelog): version 1.21.0 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.21.1
=> docs(changelog): version 1.21.1 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.22.0
=> docs(changelog): version 1.22.0 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.22.1
=> docs(changelog): version 1.22.1 [citest skip]

.github/workflows/python-unit-test.yml, tox.ini
Add new pcs upstream versions to python unit test matrix
=> ci: update pcs test matrix

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.23.0
=> docs(changelog): version 1.23.0 [citest skip]
